# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AmazonChimeSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AmazonChimeSDK

  target 'AmazonChimeSDKTests' do
    # Pods for testing
  end

end

target 'AmazonChimeSDKPods' do
  use_frameworks!

  # Pods for AmazonChimeSDKPods
  pod 'AmazonChimeSDKMedia-Bitcode', '0.15.2'

end

