# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AmazonChimeSDKPods' do
  use_frameworks!

  # Pods for AmazonChimeSDKPods
  pod 'AmazonChimeSDKMedia-Bitcode', '0.15.2'

end

target 'AmazonChimeSDKPodsTests' do
  use_frameworks!
  # Pods for testing
  pod 'AmazonChimeSDKMedia-Bitcode', '0.15.2'
end

